---
- assert: { that: vm_name is defined }
- import_tasks: volume.yml
- import_tasks: domain.yml
- name: Start domain
  virt: name={{ vm_name }} state=running
  when: vm_start is defined and vm_start == True
- name: Set VM to autostart
  virt: name={{ vm_name }} command=autostart
  when: vm_start is defined and vm_start == True
